server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/budget
spring.datasource.username=budget
spring.datasource.password=budget
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml