--liquibase formatted sql

--changeset petrichor:001-create-users
CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(254) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ
);

CREATE UNIQUE INDEX ux_users_email_lower
    ON users (LOWER(email));


--changeset petrichor:002-create-accounts
CREATE TABLE accounts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    name       VARCHAR(80)  NOT NULL,
    currency   CHAR(3)      NOT NULL,
    archived   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_accounts_user_created_at
    ON accounts (user_id, created_at DESC);

CREATE INDEX ix_accounts_user_archived_created_at
    ON accounts (user_id, archived, created_at DESC);


--changeset petrichor:003-create-categories
CREATE TABLE categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    name       VARCHAR(60)  NOT NULL,
    type       VARCHAR(10)  NOT NULL,
    archived   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_categories_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT chk_categories_type
        CHECK (type IN ('EXPENSE', 'INCOME'))
);

CREATE INDEX ix_categories_user_type_created_at
    ON categories (user_id, type, created_at DESC);

CREATE UNIQUE INDEX ux_categories_user_type_name_active
    ON categories (user_id, type, LOWER(name))
    WHERE archived = FALSE;


--changeset petrichor:004-create-transactions
CREATE TABLE transactions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT          NOT NULL,
    category_id   BIGINT,
    type          VARCHAR(10)     NOT NULL,
    merchant_name VARCHAR(120),
    note          VARCHAR(500),
    occurred_at   TIMESTAMPTZ     NOT NULL,
    amount        NUMERIC(19, 8)  NOT NULL,
    currency      CHAR(3)         NOT NULL,
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ,

    CONSTRAINT fk_transactions_account
        FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,

    CONSTRAINT fk_transactions_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,

    CONSTRAINT chk_transactions_type
        CHECK (type IN ('EXPENSE', 'INCOME')),

    CONSTRAINT chk_transactions_amount
        CHECK (amount >= 0)
);

CREATE INDEX ix_transactions_account_occurred_at
    ON transactions (account_id, occurred_at DESC);

CREATE INDEX ix_transactions_account_type_occurred_at
    ON transactions (account_id, type, occurred_at DESC);

CREATE INDEX ix_transactions_category_occurred_at
    ON transactions (category_id, occurred_at DESC);

CREATE INDEX ix_transactions_occurred_at
    ON transactions (occurred_at DESC);


--changeset petrichor:005-create-budget-plans
CREATE TABLE budget_plans
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT          NOT NULL,
    period_start        DATE            NOT NULL,
    period_end          DATE            NOT NULL,
    currency            CHAR(3)         NOT NULL,
    total_expense_limit NUMERIC(19, 8)  NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,

    CONSTRAINT fk_budget_plans_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT chk_budget_plans_period
        CHECK (period_end >= period_start),

    CONSTRAINT chk_budget_plans_total_expense_limit
        CHECK (total_expense_limit >= 0)
);

CREATE UNIQUE INDEX ux_budget_plans_user_period_currency
    ON budget_plans (user_id, period_start, period_end, currency);

CREATE INDEX ix_budget_plans_user_period_start
    ON budget_plans (user_id, period_start DESC);


--changeset petrichor:006-create-budget-plan-category-limits
CREATE TABLE budget_plan_category_limits
(
    plan_id       BIGINT         NOT NULL,
    category_id   BIGINT         NOT NULL,
    limit_amount  NUMERIC(19, 8) NOT NULL,

    CONSTRAINT pk_budget_plan_category_limits
        PRIMARY KEY (plan_id, category_id),

    CONSTRAINT fk_bpcl_plan
        FOREIGN KEY (plan_id) REFERENCES budget_plans (id) ON DELETE CASCADE,

    CONSTRAINT fk_bpcl_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,

    CONSTRAINT chk_bpcl_limit_amount
        CHECK (limit_amount >= 0)
);


--changeset petrichor:007-create-forecast-runs
CREATE TABLE forecast_runs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT       NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    model_type         VARCHAR(20)  NOT NULL,
    horizon_days       INTEGER      NOT NULL,
    history_days       INTEGER,
    include_income     BOOLEAN      NOT NULL DEFAULT TRUE,
    confidence_levels  JSONB,
    metrics            JSONB,
    error_message      TEXT,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ,

    CONSTRAINT fk_forecast_runs_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT chk_forecast_runs_status
        CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),

    CONSTRAINT chk_forecast_runs_model_type
        CHECK (model_type IN ('STUB', 'PROPHET', 'ARIMA', 'ETS', 'LSTM', 'OTHER')),

    CONSTRAINT chk_forecast_runs_horizon_days
        CHECK (horizon_days BETWEEN 1 AND 365),

    CONSTRAINT chk_forecast_runs_history_days
        CHECK (history_days IS NULL OR history_days BETWEEN 30 AND 2000),

    CONSTRAINT chk_forecast_runs_confidence_levels_json
        CHECK (
            confidence_levels IS NULL
                OR jsonb_typeof(confidence_levels) = 'array'
            ),

    CONSTRAINT chk_forecast_runs_metrics_json
        CHECK (
            metrics IS NULL
                OR jsonb_typeof(metrics) = 'object'
            )
);

CREATE INDEX ix_forecast_runs_user_created_at
    ON forecast_runs (user_id, created_at DESC);

CREATE INDEX ix_forecast_runs_user_status_created_at
    ON forecast_runs (user_id, status, created_at DESC);


--changeset petrichor:008-create-forecast-points
CREATE TABLE forecast_points
(
    run_id        BIGINT         NOT NULL,
    date          DATE           NOT NULL,
    currency      CHAR(3)        NOT NULL,
    expense_p50   NUMERIC(19, 8),
    expense_p90   NUMERIC(19, 8),
    income_p50    NUMERIC(19, 8),
    income_p90    NUMERIC(19, 8),

    CONSTRAINT pk_forecast_points
        PRIMARY KEY (run_id, date),

    CONSTRAINT fk_forecast_points_run
        FOREIGN KEY (run_id) REFERENCES forecast_runs (id) ON DELETE CASCADE,

    CONSTRAINT chk_forecast_points_expense_p50
        CHECK (expense_p50 IS NULL OR expense_p50 >= 0),

    CONSTRAINT chk_forecast_points_expense_p90
        CHECK (expense_p90 IS NULL OR expense_p90 >= 0),

    CONSTRAINT chk_forecast_points_income_p50
        CHECK (income_p50 IS NULL OR income_p50 >= 0),

    CONSTRAINT chk_forecast_points_income_p90
        CHECK (income_p90 IS NULL OR income_p90 >= 0)
);


--changeset petrichor:009-create-alerts
CREATE TABLE alerts
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT       NOT NULL,
    type                     VARCHAR(20)  NOT NULL,
    severity                 VARCHAR(20)  NOT NULL,
    status                   VARCHAR(20)  NOT NULL,
    date                     DATE,
    message                  TEXT         NOT NULL,
    related_forecast_run_id  BIGINT,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ,

    CONSTRAINT fk_alerts_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT fk_alerts_related_forecast_run
        FOREIGN KEY (related_forecast_run_id) REFERENCES forecast_runs (id) ON DELETE SET NULL,

    CONSTRAINT chk_alerts_type
        CHECK (type IN ('OVERSPEND_RISK', 'CASHFLOW_RISK', 'ANOMALY', 'OTHER')),

    CONSTRAINT chk_alerts_severity
        CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),

    CONSTRAINT chk_alerts_status
        CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'CLOSED'))
);

CREATE INDEX ix_alerts_user_status_created_at
    ON alerts (user_id, status, created_at DESC);

CREATE INDEX ix_alerts_user_date
    ON alerts (user_id, date);


--changeset petrichor:010-create-scenarios
CREATE TABLE scenarios
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT       NOT NULL,
    name                    VARCHAR(120) NOT NULL,
    type                    VARCHAR(40)  NOT NULL,
    parameters              JSONB        NOT NULL,
    run_forecast            BOOLEAN      NOT NULL DEFAULT TRUE,
    result_forecast_run_id  BIGINT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_scenarios_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT fk_scenarios_result_forecast_run
        FOREIGN KEY (result_forecast_run_id) REFERENCES forecast_runs (id) ON DELETE SET NULL,

    CONSTRAINT chk_scenarios_type
        CHECK (type IN ('PERCENT_BY_CATEGORY', 'ADD_RECURRING_PAYMENT', 'ONE_TIME_ADJUSTMENT', 'OTHER')),

    CONSTRAINT chk_scenarios_parameters_json
        CHECK (jsonb_typeof(parameters) = 'object')
);

CREATE INDEX ix_scenarios_user_created_at
    ON scenarios (user_id, created_at DESC);


--changeset petrichor:011-create-import-jobs
CREATE TABLE import_jobs
(
    job_id         VARCHAR(64)  PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    format         VARCHAR(20)  NOT NULL,
    payload        TEXT         NOT NULL,
    dry_run        BOOLEAN      NOT NULL DEFAULT TRUE,
    status         VARCHAR(20)  NOT NULL,
    error_message  TEXT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,

    CONSTRAINT fk_import_jobs_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT chk_import_jobs_format
        CHECK (format IN ('CSV', 'JSON', 'BANK_EXPORT', 'OTHER')),

    CONSTRAINT chk_import_jobs_status
        CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED'))
);

CREATE INDEX ix_import_jobs_user_created_at
    ON import_jobs (user_id, created_at DESC);


--changeset petrichor:012-create-idempotency-records
CREATE TABLE idempotency_records
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_key        VARCHAR(128) NOT NULL,
    operation        VARCHAR(120) NOT NULL,
    idempotency_key  VARCHAR(128) NOT NULL,
    request_hash     VARCHAR(128) NOT NULL,
    response_status  INTEGER      NOT NULL,
    response_body    JSONB,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    expires_at       TIMESTAMPTZ,

    CONSTRAINT ux_idempotency_scope_operation_key
        UNIQUE (scope_key, operation, idempotency_key)
);

CREATE INDEX ix_idempotency_expires_at
    ON idempotency_records (expires_at);


--changeset petrichor:013-create-daily-aggregates-view
CREATE VIEW v_daily_aggregates AS
SELECT
    a.user_id                                                  AS user_id,
    (t.occurred_at AT TIME ZONE 'UTC')::DATE                   AS date,
    t.currency                                                 AS currency,
    SUM(CASE WHEN t.type = 'EXPENSE' THEN t.amount ELSE 0 END) AS expense_total,
    SUM(CASE WHEN t.type = 'INCOME'  THEN t.amount ELSE 0 END) AS income_total
FROM transactions t
         JOIN accounts a ON a.id = t.account_id
GROUP BY
    a.user_id,
    (t.occurred_at AT TIME ZONE 'UTC')::DATE,
    t.currency;